### ISSUE TITLE
no need to specify port number, bandwidth should be optional

### ISSUE THREAD

**Issue by alexpyattaev** [KOROBYAKA/WTF#2]
We will always use default port in our tests, please hardcode it.
Provide a reasonable default bandwidth, e.g. 1 Gbps, so it does not have to be specified.
Also I suggest that starting without arguments should not be allowed (never provide two ways to do the same thing)

**Comment by KOROBYAKA** [comment]
Now bandwidth has default value 0, so bandwidth is not limited by code.
